"""add exercise catalog fields

Revision ID: 96b7c62497ff
Revises: 5f71fcde9cef
Create Date: 2026-08-24 12:34:31.502946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b7c62497ff'
down_revision: Union[str, None] = '5f71fcde9cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    difficulty_enum = sa.Enum('beginner', 'intermediate', 'advanced', name='difficulty')
    exercise_status_enum = sa.Enum('available', 'coming_soon', name='exercise_status')
    difficulty_enum.create(op.get_bind(), checkfirst=True)
    exercise_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('exercises', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('exercises', sa.Column('difficulty', difficulty_enum, nullable=False))
    op.add_column('exercises', sa.Column('muscle_group', sa.String(), nullable=False))
    op.add_column('exercises', sa.Column('status', exercise_status_enum, nullable=False))
    op.add_column('exercises', sa.Column('required_keypoints', sa.JSON(), nullable=True))
    op.add_column('exercises', sa.Column('default_config', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'exercises', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='unique')
    op.drop_column('exercises', 'default_config')
    op.drop_column('exercises', 'required_keypoints')
    op.drop_column('exercises', 'status')
    op.drop_column('exercises', 'muscle_group')
    op.drop_column('exercises', 'difficulty')
    op.drop_column('exercises', 'slug')

    sa.Enum(name='exercise_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='difficulty').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
